kind: ConfigMap
apiVersion: v1
metadata:
  name: REPLACEMENT_NAME
  namespace: REPLACEMENT_NAMESPACE
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.19.0",
        "id": "REPLACEMENT_NAME",
        "REPLACEMENT_NAMESPACE": {
          "class": "Tenant",
          "REPLACEMENT_NAMESPACE_REPLACEMENT_SVC_NAME": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "REPLACEMENT_BIGIP_VS_IP_ADDR"
              ],
              "virtualPort": 80,
              "pool": "REPLACEMENT_NAMESPACE_REPLACEMENT_SVC_NAME_pool"
            },
            "REPLACEMENT_NAMESPACE_REPLACEMENT_SVC_NAME_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }