kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1100
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1100",
        "perftestzone1100": {
          "class": "Tenant",
          "perftestzone1100": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.3"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1100_app_svc_pool"
            },
            "perftestzone1100_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1101
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1101",
        "perftestzone1101": {
          "class": "Tenant",
          "perftestzone1101": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.4"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1101_app_svc_pool"
            },
            "perftestzone1101_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1102
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1102",
        "perftestzone1102": {
          "class": "Tenant",
          "perftestzone1102": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.5"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1102_app_svc_pool"
            },
            "perftestzone1102_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1103
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1103",
        "perftestzone1103": {
          "class": "Tenant",
          "perftestzone1103": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.6"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1103_app_svc_pool"
            },
            "perftestzone1103_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1104
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1104",
        "perftestzone1104": {
          "class": "Tenant",
          "perftestzone1104": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.7"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1104_app_svc_pool"
            },
            "perftestzone1104_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1105
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1105",
        "perftestzone1105": {
          "class": "Tenant",
          "perftestzone1105": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.8"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1105_app_svc_pool"
            },
            "perftestzone1105_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1106
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1106",
        "perftestzone1106": {
          "class": "Tenant",
          "perftestzone1106": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.9"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1106_app_svc_pool"
            },
            "perftestzone1106_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1107
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1107",
        "perftestzone1107": {
          "class": "Tenant",
          "perftestzone1107": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.10"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1107_app_svc_pool"
            },
            "perftestzone1107_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1108
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1108",
        "perftestzone1108": {
          "class": "Tenant",
          "perftestzone1108": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.11"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1108_app_svc_pool"
            },
            "perftestzone1108_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: perftestzone1109
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "perftestzone1109",
        "perftestzone1109": {
          "class": "Tenant",
          "perftestzone1109": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.12"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "perftestzone1109_app_svc_pool"
            },
            "perftestzone1109_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }

