apiVersion: v1
kind: Namespace
metadata:
  name: cistest001
  labels:
    cis_scanner: cistest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-svc-1-app
  name: app-svc-1-app
  namespace: cistest001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-svc-1-app
  template:
    metadata:
      labels:
        app: app-svc-1-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc-1-app
    cis.f5.com/as3-tenant: cistest001
    cis.f5.com/as3-app: app-svc-1-app
    cis.f5.com/as3-pool: app-svc-1-app-pool
  name: app-svc-1
  namespace: cistest001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-svc-1-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: cistest002
  labels:
    cis_scanner: cistest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-svc-1-app
  name: app-svc-1-app
  namespace: cistest002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-svc-1-app
  template:
    metadata:
      labels:
        app: app-svc-1-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc-1-app
    cis.f5.com/as3-tenant: cistest002
    cis.f5.com/as3-app: app-svc-1-app
    cis.f5.com/as3-pool: app-svc-1-app-pool
  name: app-svc-1
  namespace: cistest002
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-svc-1-app
  sessionAffinity: None
  type: ClusterIP
---
